### PR TITLE
Adding new section on Java client

### PR DESCRIPTION
**Pull request by RBlafford**
- Removing cluster installation page.. we expect all clients
  to try concord out using the vagrant box
@senior7515

### CODE REVIEW

**Comment by RBlafford** [comment]
I believe the installation section is incomplete mostly because we don't currently have a method of doing this

**Comment by senior7515** [comment]
Yeah, that's fine. for the java installation to be incomplete. 

Can you also update the python code with a real methods from python. 

They are missing the self parameter. Look at our source code and then at the docs.

**Comment by senior7515** [comment]
LGTM. otherwise.

**Comment by senior7515** [comment]
can you merge and stuff. and push to the website.

**Pull request merged**
